# syntax=docker/dockerfile:1

FROM node:14.15.3
ENV NODE_ENV=production

WORKDIR /product-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

CMD [ "node", "server.js" ]