# syntax=docker/dockerfile:1

FROM node:14

ENV NODE_ENV=production

WORKDIR /product-service

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

EXPOSE 8082

CMD [ "node", "server.js" ]